name: flutter_simple_form
description: Flutter Simple Form
version: 0.0.5
homepage: https://github.com/Naboska/flutter_simple_form

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: